### ISSUE TITLE
minetestmapper only works for small maps

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetestmapper#16]
l tried the minetestmapper on my main world.
At first it told me that the backend setting is missing.
So l added --backend sqlite3 after the command. (map.sqlite always means sqlite3 backend, doesn't it?)
After waiting a few seconds and listening to these noises from my pc caused by minetestmapper
it crashed with memory access error as reason.
Then, when l clicked on my firefox window, these noises came again and l needed to wait for a few seconds.
Does minetestmapper work for big worlds if the memory is a bit small?

**Comment by ShadowNinja** [comment]
The mapper maps the **whole** generated world.  This can require an enormous amount of memory (Up to 18 GB or so) if you have even one block loaded far away from spawn.

@sfan5: This behavior should be reverted.  I've heard of this issue many times.

**Comment by HybridDog** [comment]
Thanks, maybe you can generate parts (each mapchunk), save them in pngs and then put the map together.

**Comment by est31** [comment]
Or even better, generate the small parts (eg 512x512 square, 16x16 is too small I think), then make a sloppy map.

**Comment by est31** [comment]
I think it doesnt abort.

**Comment by HybridDog** [comment]
And can l run the command that it aborts if there's nothing?

**Comment by est31** [comment]
@HybridDog what makes you believe the issue got fixed?

**Comment by HybridDog** [comment]
it is possible to set the geometry

**Comment by Khyota** [comment]
It segfaults if you try to generate a map if you've explored a large area that doesn't fit into a square. Setting geometry is a workaround but it doesn't fix the problem.

**Comment by HybridDog** [comment]
Actually a very big png file should take less than a gigabyte.

**Comment by Rogier-5** [comment]
Some background information for people affected by this bug:
The problem is caused by sheer image size, and by a bug in the drawing library (libgd), which can't handle huge images. 

62000x62000 pixels is 3.8 G-pixels (3844 million). If every pixel needs 4 bytes while being generated, that means 12GB memory for just the image. 32-bit machines cannot even ever hope to generate such an image, or, if it *could* be generated, load it into a viewer for that matter... (although technically it would be possible, regular software is not designed or written to handle images larger than the available address space). On 32-bit systems, the practical limit for image size is probably in the vicinity of 23000x23000 (or 46000x11500, etc: about 536 million pixels). Of course YMMV.

On 64-bit platforms, apart from the memory issue (most people don't have 12GB of memory, and there are reports of memory consumption closer to 20GB, so swapping would probably make generation slooooow), the bug in the drawing library prevents generating images with more than 2 G-pixels, which is about 46300x46300 (or 62000x34600, etc). So that's about the current limit on 64-bit systems.

So for the moment, the best option is to generate such images in sections.
As huge images of such sizes are often impractical anyway, you might also want to consider https://github.com/est31/leaftest. See http://daconcepts.com/vanessa/hobbies/minetest/worldmaps/Survival_World/map.html for an example.

BTW: wrt image size: a 62000x62000 png file of a full world (no large ungenerated areas with better-than-average compression) could probably be close to 1.3GB (aka GiB). Be aware that png is compressed: the uncompressed image, ready for viewing, is still 12GB. From a non-representative sample, I'd expect about 300-350 KB file size per million pixels (per area of 1000x1000 for example). If large parts of the world have not been generated, the average size per million pixels will be smaller of course.

**Comment by HybridDog** [comment]
thanks for showing me leaftest, l still like onomatopoeia, but it's extremely slow
https://github.com/Zeg9/onomatopoeia

**Comment by Khyota** [comment]
After realizing the gd limit i set map_generation_limit = 21806 so that I can never create a world that will exceed what I can map with a single image. This number leaves just enough headroom for mapping with --drawscale and --tiles block (using Rogier-5's mapper). Image size is 46205x46195. I'm using /emergeblocks (-21712,0,-21712) (21727,0,21727) to generate a one block high section of the entire world.

**Comment by sfan5** [comment]
``--geometry`` is precisely for the case that you need to cut your map into several small ones.
You might also want to use something like leaftest in that case
