### ISSUE TITLE
Option for fixed image size

### ISSUE THREAD

**Issue by neko259** [minetest/minetestmapper#49]
I am trying to use some tile html viewer to paint a map of tile images as a map, instead of trying to generate it as one. But the mapper supposedly tries to limit the image size to the actual existing map, and the tiles have different size. E.g. if I specify 1000x1000 tiles, some of them make 32x32 empty images (for the area not generated), some 800x1000, and some even 1008x1008 (not sure why it's bigger then specified geometry). Obviously such images cannot be used to be tiled along as a map.

**Comment by expertmm** [comment]
I agree, some kind of predictability is needed for making tools that use the output of minetestmapper. If the map was a fixed size, that would be ideal. Another thing that would be helpful is some standard output such as:
```yaml
min_chunkx: -48
min_chunkz: -219
max_chunkx: 67
max_chunkz: 86
is_empty: False
total_generated_count: 14
```
This is the type of output I provide with my (slower) python version [here](https://github.com/expertmm/EnlivenMinetest/blob/master/mtanalyze/minetestmapper-numpy.py) which I use for [this](https://github.com/expertmm/EnlivenMinetest/blob/master/mtanalyze/singleimage.py) because I have no other option. I forked my minetestmapper-numpy.py from [spillz'](https://forum.minetest.net/viewtopic.php?t=8730) to provide output such as above. A fixed size image would also solve the main issue, which is how the output image is actually placed on a map such as an HTML5 canvas map made of multiple chunks (that mode of my HTML5 canvas map is not working, so I have to use a single image mode).

**Comment by sfan5** [comment]
ac15bacf36f31e0fde1880fe3acc10fe3f812ff3
